version: "2"
services:
  rust:
    build: "."
    image: "rumaio/ruma-dev"
    links:
      - "postgres"
    volumes:
      - ".:/source"
      - "cargo_git:/usr/local/cargo/git"
      - "cargo_registry:/usr/local/cargo/registry"
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=test"
    volumes:
      - "pg:/var/lib/postgresql/data"
volumes:
  cargo_git: {}
  cargo_registry: {}
  pg: {}
